// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojgrprjehsamxcboxjlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZ3JwcmplaHNhbXhjYm94amx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzE2OTYsImV4cCI6MjA2NzMwNzY5Nn0.7IZCUo0iawdldtxIRA774WCNH01GyUYWA0nSBmE9oOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});